---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: amicable
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd amicable
      - go test
  - name: collatz
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd collatz
      - go test
  - name: countsunday
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd countsunday
      - go test
  - name: divisors
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd divisors
      - go test
  - name: evenfib
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd evenfib
      - go test
  - name: factdigitsum
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd factdigitsum
      - go test
  - name: factorial
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd factorial
      - go test
  - name: fibonacci
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd fibonacci
      - go test
#  - name: highdivtri
#    image: golang:1.15
#    depends_on:
#      - yamllint
#    commands:
#      - cd highdivtri
#      - go test
  - name: largestprime
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd largestprime
      - go test
  - name: largesum
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd largesum
      - go test
  - name: longestcollatz
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd longestcollatz
      - go test
  - name: mul35
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd mul35
      - go test
  - name: namescore
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd namescore
      - go test
  - name: powersum
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd powersum
      - go test
  - name: prime
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd prime
      - go test
  - name: sum
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd sum
      - go test
  - name: triangle
    image: golang:1.15
    depends_on:
      - yamllint
    commands:
      - cd triangle
      - go test
